//============================================================================
// Name        : EulerP002.cpp
// Author      : Carlos Perez
// Version     :
// Copyright   : Your copyright notice
// Description : Hello World in C++, Ansi-style
//============================================================================
/*
 * Each new term in the Fibonacci sequence is generated by adding
 * the previous two terms. By starting with 1 and 2, the first 10
 * terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed 
four million, find the sum of the even-valued terms.
 */
#include <iostream>
using namespace std;
int Fibonacci(int a,int b);
int END = 4000000;
long total = 0;
int main() {
	Fibonacci(0,1);
	cout << total << "\n";
	return 0;
}
int Fibonacci(int a,int b)
{
	total = total + a;
	if (b < END)	{return a + Fibonacci(b,(a+b));	}
	return 0;
}
